
/* **** Leaflet **** */

// Base layers
//  .. OpenStreetMap
var osm = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors', minZoom: 18, maxZoom: 24, maxNativeZoom: 19});
//  .. White background
var white = L.tileLayer("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEAAQMAAABmvDolAAAAA1BMVEX///+nxBvIAAAAH0lEQVQYGe3BAQ0AAADCIPunfg43YAAAAAAAAAAA5wIhAAAB9aK9BAAAAABJRU5ErkJggg==", {minZoom: 18, maxZoom: 24});

// Overlay layers (TMS)
var lyr = L.tileLayer('./{z}/{x}/{y}.png', {tms: true, opacity: 0.9, attribution: "", minZoom: 18, maxZoom: 24});
var mlyr = L.tileLayer('./{z}/{x}/{y}.png', {tms: true, opacity: 1, attribution: "", minZoom: 18, maxNativeZoom: 24, maxZoom: 30});
// Map
var map = L.map('map', {
	center: [32.88398788, -117.234798816],
	zoom: 18,
	minZoom: 18,
	maxZoom: 24,
	layers: [osm, lyr],
	dragging: false,
});

var miniMap = L.map('minimap', {
	center: [32.88398788, -117.234798816],
	zoom: 18,
	minZoom: 18,
	maxZoom: 30,
	maxNativeZoom: 24,
	touchZoom: false,
	doubleClickZoom: false,
	scrollWheelZoom: false,
	zoomControl: false,
	boxZoom: false,
	keyboard: false,
	zoomAnimation: false,
	layers: [mlyr],
});


var basemaps = {"OpenStreetMap": osm, "Without background": white}
var overlaymaps = {"Layer": lyr}

// Title
var title = L.control();
title.onAdd = function(map) {
	this._div = L.DomUtil.create('div', 'ctl title');
	this.update();
	return this._div;
};
title.update = function(props) {
	this._div.innerHTML = "1530_ortho.tif";
};
title.addTo(map);

// Note
var src = 'Generated by <a href="http://www.klokan.cz/projects/gdal2tiles/">GDAL2Tiles</a>, Copyright &copy; 2008 <a href="http://www.klokan.cz/">Klokan Petr Pridal</a>,  <a href="http://www.gdal.org/">GDAL</a> &amp; <a href="http://www.osgeo.org/">OSGeo</a> <a href="http://code.google.com/soc/">GSoC</a>';
var title = L.control({position: 'bottomleft'});
title.onAdd = function(map) {
	this._div = L.DomUtil.create('div', 'ctl src');
	this.update();
	return this._div;
};
title.update = function(props) {
	this._div.innerHTML = src;
};
title.addTo(map);


// Add base layers
L.control.layers(basemaps, overlaymaps, {collapsed: false}).addTo(map);

// Fit to overlay bounds (SW and NE points with (lat, lon))
map.fitBounds([[32.8835050061, -117.234528946], [32.884470754, -117.235068686]]);

var clickStart;
var miniStart;
var box;
var miniBox = L.rectangle([[0,0],[0,0]], {fill: false, color: '#3388ff'}).addTo(miniMap);
var boxes = [];
function onMouseDown(e) {
	clickStart = e.latlng;
	box = L.rectangle(L.latLngBounds(e.latlng, e.latlng), {fill: false, color: '#3388ff'}).addTo(map);
}
map.on('mousedown', onMouseDown);

function onMiniDown(e) {
	miniStart = miniMap.getBounds()._southWest;
}
miniMap.on('dragstart', onMiniDown);

function onMiniMove(e) {
	if (miniStart != null) {
		var offLat = miniMap.getBounds()._southWest.lat - miniStart.lat;
		var offLng = miniMap.getBounds()._southWest.lng - miniStart.lng;
		miniBox.setBounds([[miniBox._bounds._southWest.lat + offLat, miniBox._bounds._southWest.lng + offLng],[miniBox._bounds._northEast.lat + offLat, miniBox._bounds._northEast.lng + offLng]]);
		if (boxes.length > 0) {
			boxes[boxes.length - 1].setBounds(miniBox._bounds);
		}
		miniStart = miniMap.getBounds()._southWest;
	}
}
miniMap.on('drag', onMiniMove);
function onMiniUp(e) {
	if (miniStart != null) {
		miniStart = null;
		if (boxes.length > 0) {
			boxes[boxes.length - 1].setBounds(miniBox._bounds);
		}
	}
}
miniMap.on('dragend', onMiniUp);

miniMap.on('contextmenu', function(e) {});
map.on('contextmenu', function(e) {});

function onMouseUp(e) {
	if (box != null) {
		console.log(clickStart.toString()+" -> "+e.latlng.toString());
		box.setStyle({fill: true, color: '#114499'});
		clickStart = null;
		var area = (box._bounds._northEast.lat-box._bounds._southWest.lat) * (box._bounds._northEast.lng-box._bounds._southWest.lng);
		console.log(Math.abs(area));
		boxes.push(box)
		box = null;
	}
}
map.on('mouseup', onMouseUp);

function onMouseMove(e) {
	if (box != null) {
		box.setBounds(L.latLngBounds(e.latlng, clickStart));
		miniBox.setBounds(box._bounds);
		// console.log(clickStart.toString()+" -> "+e.latlng.toString());
		miniMap.fitBounds(box._bounds);
	}
}
map.on('mousemove', onMouseMove);

function onMouseOut(e) {
	if (box != null) {
		console.log("leave");
		box.removeFrom(map);
		clickStart = null;
		box = null;
		if (boxes.length > 0) {
			miniBox.setBounds(boxes[boxes.length - 1]._bounds);
			miniMap.fitBounds(miniBox._bounds);
		} else {
			miniBox.setBounds([[0,0],[0,0]]);
		}
	}
}
map.on('mouseout', onMouseOut);

function undoBox() {
	if (boxes.length > 0) {
		boxes[boxes.length - 1].removeFrom(map);
		boxes.pop();
		if (boxes.length > 0) {
			miniBox.setBounds(boxes[boxes.length - 1]._bounds);
			miniMap.fitBounds(miniBox._bounds);
		} else {
			miniBox.setBounds([[0,0],[0,0]]);
		}
	}
}
function clearBoxes() {
	for (i = boxes.length - 1; i >= 0; i--) {
		boxes[i].removeFrom(map);
		boxes.pop();
		miniBox.setBounds([[0,0],[0,0]]);
	}
}
